<?php $this->partial('headers/main.phtml'); ?>
<div class="container mt75">
    <div class="row login">
        <div class="width-30"></div>
        <div class="width-40">
            <div class="panel shadowocre">
                <div class="header"><span class="title">identification</span></div>
                <div class="body">
                    <div class="input-field">
                        <i class="material-icons prefix">account_circle</i>
                        <input id="login" name="login" type="text" class="validate">
                        <label for="icon_prefix">Identifiant</label>
                    </div>
                    <div class="input-field">
                        <i class="material-icons prefix">vpn_key</i>
                        <input id="password" name="password" type="password" class="validate">
                        <label for="icon_prefix">Mot de passe</label>
                    </div>
                    <p class="mt20">
                        <input type="checkbox" name="always" id="always">
                        <label for="always">Rester connecté</label>
                    </p>
                    <p class="mt20 text-right">
                        <a href="<?php echo $this->url('/lost'); ?>">Identifiants égarés ?</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="width-30"></div>
    </div>
</div>
<?php $this->partial('footers/main.phtml'); ?>
